[supervisord]
nodaemon=true

[program:xvfb]
command=Xvfb :1 -screen 0 1280x800x24
autorestart=true
priority=1

[program:x11vnc]
command=x11vnc -display :1 -forever -nopw -shared
autorestart=true
priority=2

[program:novnc]
command=websockify --web=/usr/share/novnc/ 6080 localhost:5900
autorestart=true
priority=3

[program:spoon]
command=/opt/pentaho/spoon.sh
environment=DISPLAY=":1"
autorestart=false
priority=4
startsecs=5
